version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: subject
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/conf.d:/etc/mysql/conf.d
      - ./sql/mock-schema.sql:/docker-entrypoint-initdb.d/mock-schema.sql
    networks:
      - app-network

  redis:
    image: redis:7.0.5
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
