spring:
  cache:
    type: simple
  datasource:
    url: jdbc:mysql://localhost:3306/subject?useUnicode=true&characterEncoding=UTF-8
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#  cache:
#    type: redis

#  redis:
#    host: localhost
#    port: 6379