-- 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS subject
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_general_ci;

-- 데이터베이스 사용
USE subject;

-- 테이블 생성
CREATE TABLE IF NOT EXISTS mock_data (
                                         id INT AUTO_INCREMENT PRIMARY KEY,
                                         people_name VARCHAR(255) NOT NULL COLLATE utf8mb4_general_ci,
                                         age INT NOT NULL,
                                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 샘플 데이터 삽입
INSERT INTO mock_data (people_name, age) VALUES
                                             ('json', 25),
                                             ('이영희', 30),
                                             ('박민수', 28),
                                             ('최지우', 32),
                                             ('정수진', 27),
                                             ('한예슬', 29),
                                             ('장동건', 31),
                                             ('송혜교', 26),
                                             ('강호동', 24),
                                             ('유재석', 33),
                                             ('김태희', 35),
                                             ('전지현', 22),
                                             ('이병헌', 21),
                                             ('송중기', 23),
                                             ('고소영', 34),
                                             ('김혜수', 36),
                                             ('이준기', 37),
                                             ('박보검', 38),
                                             ('김우빈', 39),
                                             ('이종석', 40),
                                             ('수지', 41),
                                             ('아이유', 42),
                                             ('박신혜', 43),
                                             ('한가인', 44),
                                             ('김지원', 45),
                                             ('정해인', 46),
                                             ('서강준', 47),
                                             ('남주혁', 48),
                                             ('차은우', 49),
                                             ('박서준', 50),
                                             ('김수현', 51),
                                             ('유승호', 52),
                                             ('이민호', 53),
                                             ('김고은', 54),
                                             ('윤아', 55),
                                             ('태연', 56),
                                             ('제니', 57),
                                             ('로제', 58),
                                             ('지수', 59),
                                             ('리사', 60),
                                             ('정국', 61),
                                             ('뷔', 62),
                                             ('지민', 63),
                                             ('슈가', 64),
                                             ('진', 65),
                                             ('RM', 66),
                                             ('제이홉', 67),
                                             ('강다니엘', 68),
                                             ('옹성우', 69),
                                             ('박지훈', 70),
                                             ('김재환', 71),
                                             ('이대휘', 72),
                                             ('박우진', 73),
                                             ('배진영', 74),
                                             ('하성운', 75),
                                             ('윤지성', 76),
                                             ('라이관린', 77),
                                             ('김세정', 78),
                                             ('김소혜', 79),
                                             ('정채연', 80),
                                             ('주결경', 81),
                                             ('최유정', 82),
                                             ('김도연', 83),
                                             ('임나영', 84),
                                             ('강미나', 85),
                                             ('김청하', 86),
                                             ('전소미', 87),
                                             ('유연정', 88),
                                             ('정은지', 89),
                                             ('손나은', 90),
                                             ('박초롱', 91),
                                             ('윤보미', 92),
                                             ('김남주', 93),
                                             ('오하영', 94),
                                             ('김세정', 95),
                                             ('미나', 96),
                                             ('모모', 97),
                                             ('사나', 98),
                                             ('쯔위', 99),
                                             ('다현', 100);
